<../../mkconfig

TARG=\
	disklabelfs.dis\
	ffsdump.dis\
	ffsfs.dis\

MODULES=\
	../lib/ffs.m\

SYSMODULES=\
	arg.m\
	bufio.m\
	daytime.m\
	draw.m\
	string.m\
	styx.m\
	styxservers.m\
	sys.m\
	tables.m\
	util0.m\

DISBIN=$ROOT/dis

<$ROOT/mkfiles/mkdis
